---
title: "Spam Classification"
author: "Greg Guranich, Coco Kusiak, and Xiang Li"
date: "5/3/2018"
output: pdf_document
---

```{r, include = FALSE}
require(mosaic)
require(xtable)
options(xtable.comment = FALSE)
load("spam.Rda")
```

#Abstract  
This study aims to find the best way to classify the non-spam emails and spam emails and compare the different classification methods, especially the methods with penalization and without penalization. The data is comprised of 4601 observations with 57 predictors. Most of the predictors indicate whether a particular word or character is frequently occuring in the email. We would like to use xx classification methods to analyse the data set, including…..Before that, we will use xxx to pre-process the data for xxx. Meanwhile, we will use cross validation to measure the performance of these methods. The results show that xx method performs best. Comparing xxx method, xx methods are more useful in the processes. Additionally, it is necessary to pre-process the data, since the highly correlated predictors might influence the results.  (add identification of predictors) 



#Aims of the project:
1. Find the best way to classify the spam and non-spam emails
2. Compare the data with pre-process and without process
3. Compare the methods that with and without penalization 
4. Identify the predictors that related with spam or non spam


#Introduction


##The Problem:  

##The Data:  


- 4,600 observations 
- 58 variables on nemail attribute frequency 
- About 40% of emails are spam 
- No missing values 


#Methods 

##preprocessing data 
###log transformed continuous
###continuous
###dummy encoded


##Classification

### Logistic regression
### Penalized logistic with lasso penalty
### Penalized logistic with ridge penalty
### Penalized logistic with elastic net penalty for equal mixing
### LDA
### QDA
### KNN
### Linear SVM
### Polynomial SVM
### Radial SVM
















#Results  













#Discussion  





